name=AdvancedRotaryEncoder
version=1.0.1
author=Ruben Paul Thomsen
maintainer=Ruben Paul Thomsen
sentence=Lightweight rotary encoder library with button events, acceleration and interrupt support.
paragraph=Supports A/B rotary encoders, push buttons, click, double click, long press, repeat, optional acceleration, event queue, and polling-first operation with optional interrupt support.
category=Signal Input/Output
url=https://github.com/RPaulT/RotaryEncoder
architectures=*